version: "2"

tasks:
  default:
    cmds:
      - echo "No default task."
    silent: true

  bootstrap:
    cmds:
      - brew install pipenv
      - pip3 install pre-commit
      - pre-commit install
      - pipenv install --dev
# clean:
# 	rm -rf ${CURDIR}/build ${CURDIR}/dist ${CURDIR}/*.egg-info

# cleanall:	clean
# 	# Nuke the env
# 	rm -rf ${CURDIR}/env

# run:
# 	${CURDIR}/env/bin/python3 ${CURDIR}/lib/main.py

# test:
# ${CURDIR}/env/bin/python3 ${CURDIR}/lib/test.py
