version: "2"

tasks:
  default:
    cmds:
      - echo "No default task."
    silent: true

  bootstrap:
    cmds:
      - brew install pipenv
      - pip3 install pre-commit
      - pre-commit install
      - pipenv install --dev
  clean:
    cmds:
      - rm -rf ./build ./dist ./*.egg-info

  run:
    cmds:
      - pipenv run python main.py

  test:
    cmds:
      - echo LOOOL
    silent: true
